// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleAcceptReturn *ebpf.ProgramSpec `ebpf:"handle_accept_return"`
	HandleExit         *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFork         *ebpf.ProgramSpec `ebpf:"handle_fork"`
	HandlePamAuth      *ebpf.ProgramSpec `ebpf:"handle_pam_auth"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	MonitoredPorts *ebpf.MapSpec `ebpf:"monitored_ports"`
	PidToIp        *ebpf.MapSpec `ebpf:"pid_to_ip"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	MonitoredPorts *ebpf.Map `ebpf:"monitored_ports"`
	PidToIp        *ebpf.Map `ebpf:"pid_to_ip"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.MonitoredPorts,
		m.PidToIp,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleAcceptReturn *ebpf.Program `ebpf:"handle_accept_return"`
	HandleExit         *ebpf.Program `ebpf:"handle_exit"`
	HandleFork         *ebpf.Program `ebpf:"handle_fork"`
	HandlePamAuth      *ebpf.Program `ebpf:"handle_pam_auth"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleAcceptReturn,
		p.HandleExit,
		p.HandleFork,
		p.HandlePamAuth,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
