// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sshmonPidCtx struct {
	_             structs.HostLayout
	RemoteIp      uint32
	_             [4]byte
	StartNs       uint64
	AuthAttempted uint8
	_             [7]byte
}

// loadSshmon returns the embedded CollectionSpec for sshmon.
func loadSshmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SshmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sshmon: %w", err)
	}

	return spec, err
}

// loadSshmonObjects loads sshmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sshmonObjects
//	*sshmonPrograms
//	*sshmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSshmonObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSshmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sshmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sshmonSpecs struct {
	sshmonProgramSpecs
	sshmonMapSpecs
	sshmonVariableSpecs
}

// sshmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sshmonProgramSpecs struct {
	HandleAcceptFexit     *ebpf.ProgramSpec `ebpf:"handle_accept_fexit"`
	HandleAcceptKretprobe *ebpf.ProgramSpec `ebpf:"handle_accept_kretprobe"`
	HandleExit            *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFork            *ebpf.ProgramSpec `ebpf:"handle_fork"`
	HandlePamAuth         *ebpf.ProgramSpec `ebpf:"handle_pam_auth"`
}

// sshmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sshmonMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	MonitoredPorts *ebpf.MapSpec `ebpf:"monitored_ports"`
	PidCtxMap      *ebpf.MapSpec `ebpf:"pid_ctx_map"`
}

// sshmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sshmonVariableSpecs struct {
	AggressiveMode     *ebpf.VariableSpec `ebpf:"aggressive_mode"`
	PreauthShortConnNs *ebpf.VariableSpec `ebpf:"preauth_short_conn_ns"`
}

// sshmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSshmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type sshmonObjects struct {
	sshmonPrograms
	sshmonMaps
	sshmonVariables
}

func (o *sshmonObjects) Close() error {
	return _SshmonClose(
		&o.sshmonPrograms,
		&o.sshmonMaps,
	)
}

// sshmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSshmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type sshmonMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	MonitoredPorts *ebpf.Map `ebpf:"monitored_ports"`
	PidCtxMap      *ebpf.Map `ebpf:"pid_ctx_map"`
}

func (m *sshmonMaps) Close() error {
	return _SshmonClose(
		m.Events,
		m.MonitoredPorts,
		m.PidCtxMap,
	)
}

// sshmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSshmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type sshmonVariables struct {
	AggressiveMode     *ebpf.Variable `ebpf:"aggressive_mode"`
	PreauthShortConnNs *ebpf.Variable `ebpf:"preauth_short_conn_ns"`
}

// sshmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSshmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type sshmonPrograms struct {
	HandleAcceptFexit     *ebpf.Program `ebpf:"handle_accept_fexit"`
	HandleAcceptKretprobe *ebpf.Program `ebpf:"handle_accept_kretprobe"`
	HandleExit            *ebpf.Program `ebpf:"handle_exit"`
	HandleFork            *ebpf.Program `ebpf:"handle_fork"`
	HandlePamAuth         *ebpf.Program `ebpf:"handle_pam_auth"`
}

func (p *sshmonPrograms) Close() error {
	return _SshmonClose(
		p.HandleAcceptFexit,
		p.HandleAcceptKretprobe,
		p.HandleExit,
		p.HandleFork,
		p.HandlePamAuth,
	)
}

func _SshmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sshmon_x86_bpfel.o
var _SshmonBytes []byte
